apiVersion: apps/v1
kind: Deployment
metadata:
  name: carvilla-deployment
  labels:
    app: carvilla-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carvilla-app
  template:
    metadata:
      labels:
        app: carvilla-app
    spec:
      containers:
      - name: c-carvilla:1.0.0-2
        image: raemondarellano/carvilla:1.0.0-2
        ports:
        - containerPort: 80 