apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-carvilla:1.0.0-5
  labels:
    app: app-carvilla:1.0.0-5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-carvilla:1.0.0-5
  template:
    metadata:
      labels:
        app: app-carvilla:1.0.0-5
    spec:
      containers:
      - name: c-carvilla:1.0.0-5
        image: raemondarellano/carvilla:1.0.0-5
        ports:
        - containerPort: 80 